
HashMap<String, Float> bondEnergies;

void initBondEnergies() {
  bondEnergies = new HashMap<String, Float>();
  bondEnergies.put("H - H", 432.0);
  bondEnergies.put("H - C", 411.0);
  bondEnergies.put("H - Si", 148.0);
  bondEnergies.put("H - N", 386.0);
  bondEnergies.put("H - O", 459.0);
  bondEnergies.put("H - S", 363.0);
  bondEnergies.put("H - F", 565.0);
  bondEnergies.put("H - Cl", 428.0);
  bondEnergies.put("H - Br", 362.0);
  bondEnergies.put("C - C", 346.0);
  bondEnergies.put("C -- C", 602.0);
  bondEnergies.put("C --- C", 835.0);
  bondEnergies.put("C - Si", 318.0);
  bondEnergies.put("C - N", 305.0);
  bondEnergies.put("C -- N", 615.0);
  bondEnergies.put("C --- N", 887.0);
  bondEnergies.put("C - O", 358.0);
  bondEnergies.put("C -- O", 799.0);
  bondEnergies.put("C --- O", 1072.0);
  bondEnergies.put("C - S", 272.0);
  bondEnergies.put("C -- S", 573.0);
  bondEnergies.put("C - F", 485.0);
  bondEnergies.put("C - Cl", 327.0);
  bondEnergies.put("C - Br", 285.0);
  bondEnergies.put("Si - Si", 222.0);
  bondEnergies.put("Si - N", 355.0);
  bondEnergies.put("Si - O", 452.0);
  bondEnergies.put("Si - S", 293.0);
  bondEnergies.put("Si - F", 565.0);
  bondEnergies.put("Si - Cl", 381.0);
  bondEnergies.put("Si - Br", 310.0);
  bondEnergies.put("N - N", 167.0);
  bondEnergies.put("N -- N", 418.0);
  bondEnergies.put("N --- N", 942.0);
  bondEnergies.put("N - O", 201.0);
  bondEnergies.put("N -- O", 607.0);
  bondEnergies.put("N - F", 283.0);
  bondEnergies.put("N - Cl", 313.0);
  bondEnergies.put("O - O", 142.0);
  bondEnergies.put("O -- O", 494.0);
  bondEnergies.put("O - F", 190.0);
  bondEnergies.put("S - O", 100.0);
  bondEnergies.put("S -- O", 522.0);
  bondEnergies.put("S - S", 226.0);
  bondEnergies.put("S -- S", 425.0);
  bondEnergies.put("S - F", 284.0);
  bondEnergies.put("S - Cl", 255.0);
  bondEnergies.put("F - F", 155.0);
  bondEnergies.put("Cl - Cl", 240.0);
  bondEnergies.put("Br - Br", 190.0);
  bondEnergies.put("Fe - O", 400.0);
  bondEnergies.put("Na - O", 257.0);
  bondEnergies.put("Na - Na", 77.0);
  bondEnergies.put("Na - Cl", 410.0);
  
}
